socketio/socket.io

- package.json
> package: debug v2.1.0

- test/socket.io.js
Checks for a similar case as reported in https://github.com/Automattic/socket.io/issues/1621
> Add test for reconnection after server restarts

- LICENSE
Only made 1 change:
1) Modified the license to include a range with the current year.
No other changes made.
> update license with up-to-date year range

- lib/index.js
- test/socket.io.js
> Allowing a custom function for opts.allowRequest

- examples/chat/public/main.js
> fixed a typo in the example code

- Readme.md
This fix is based on https://github.com/socketio/socket.io/pull/2302 .
> Update redirects in README

- examples/chat/index.js
- add a validation
- remove an unused variable.
> Improve the chat demo

- Readme.md
- package.json
> Add badges showing dependency status

- lib/socket.js
> fix typo word :)

- package.json
- test/fixtures/server-close.js
- test/socket.io.js
Related https://github.com/socketio/socket.io/issues/2069, https://github.com/socketio/engine.io/pull/378
> Add a test for graceful shutdown

- Readme.md
Added the documentation for Socket#disconnect, issue #2400.
> Documentation

- gulpfile.js
- test/socket.io.js
> add quote to exec paths, prevent error when spaces in path

- examples/chat/package.json
updated the express version, addressing #2152
the example works fine with new version express
> updated express version to express 4

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
(and suddenly all those issues will disappear)
> Add Github issue and PR templates

- lib/socket.js
Comment about https://github.com/Automattic/socket.io/commit/3f72dd3322bcefff07b5976ab817766e421d237b
> Comment connected socket availability for adapters

- lib/index.js
Following https://github.com/socketio/socket.io-client/pull/1025
Closes https://github.com/socketio/socket.io/issues/2762
> Update client location and serve minified file

- Readme.md
> Add install script on Readme.md

- lib/socket.js
> micro-optimisations

- LICENSE
> [chore] Update copyright year LICENSE to 2017

- .github/ISSUE_TEMPLATE.md
> Update issue template with fiddle

- docs/README.md
- docs/emit.md
> Add emit cheatsheet

- docs/API.md
> Fix documentation for `local` flag

- examples/whiteboard/README.md
- examples/whiteboard/index.js
- examples/whiteboard/package.json
- examples/whiteboard/public/index.html
- examples/whiteboard/public/main.js
- examples/whiteboard/public/style.css
> Implement whiteboard example

- examples/cluster-haproxy/README.md
- examples/cluster-haproxy/docker-compose.yml
- examples/cluster-haproxy/haproxy/Dockerfile
- examples/cluster-haproxy/haproxy/haproxy.cfg
- examples/cluster-haproxy/server/Dockerfile
- examples/cluster-haproxy/server/index.js
- examples/cluster-haproxy/server/package.json
- examples/cluster-haproxy/server/public/index.html
- examples/cluster-haproxy/server/public/main.js
- examples/cluster-haproxy/server/public/style.css
> Add haproxy cluster example

- docs/API.md
This is documentation for the server code, and the commented code demonstrates the client's response.
Update the wording to match.
> fix mismatch between code example and docs

- lib/index.js
- package.json
Following https://github.com/socketio/socket.io/pull/2829
> Bump socket.io-adapter to version 1.0.0

- docs/API.md
> `namespace`'s event: 'connect' returns `socket`

- docs/API.md
With this guidance, users can learn how to assign custom socket ids to connections on the server side.
> Adding namespace.engine.generateId option

- lib/index.js
> Update path of client file

- examples/webpack-build-server/lib/index.js
- examples/webpack-build-server/package.json
- examples/webpack-build-server/support/webpack.config.js
Closes https://github.com/socketio/socket.io/issues/2951.
> Update Webpack server example

- docs/emit.md
io.emit was missing in the cheat sheet.
> Added io.emit

- lib/namespace.js
- lib/socket.js
- package.json
Closes https://github.com/socketio/socket.io/issues/2996
> reset rooms object before broadcasting from namespace

- examples/chat/index.js
getting rid of github warning of using path.join
> getting rid of github warning

- docs/API.md
> Fix typo in API docs

- docs/API.md
> Found a grammar mistake in the API documentation

- examples/whiteboard/public/main.js
Added support for touch to the whiteboard example.
Touch is not working on the whiteboard example
Added support for touch in whiteboard example
> Added Touch Support

- Readme.md
> Adjusting Sauce Labs name

- .github/PULL_REQUEST_TEMPLATE.md
PR template has "behavior" spelled "behaviour"
PR template now has "behavior"  spelled correctly
> Fixes behavior typo in PR template

- lib/client.ts
No strict type checking for few cases in `if` expressions
added strict type checks
> add: strict type check in if expressions

- Readme.md
No change in behavior.
No change in behavior.
No related issues.
> Added instructions for installing the package with yarn in the README.md file.

- .github/workflows/ci.yml
> Adding Node.js 15 CI

- Readme.md
> change in readme

- .github/workflows/ci.yml
The examples aren't built by CI.
The examples that can be built are now built as part of CI.
Opening this to ensure that PRs like #3855 are checked as part of CI.
> Add example building to CI
