- lib/index.js
- test/socket.io.js
Requests without an Origin header previously caused an exception to be thrown if the allowed origins passed to the constructor was set to a dynamic function. Omitted origins are now set to an asterisk and passed properly to the origins function.
This fixes issue #1919.
A test for this case is included.
> Allow null or undefined origins when allowed origins is a function

- test/socket.io.js
Tests the following behavior with the existing volatility implementation:
- Volatile events can be sent
- Volatile events are not sent after sending a regular event (in the same tick)
- Normal events can be queued normally after a successful (not dropped) volatile event
- Only one volatile should be sent when more than one sent consecutively
All these properties are tested both on the polling and ws transports.
> Added tests for volatile

- Readme.md
- lib/client.js
- lib/socket.js
- package.json
- test/socket.io.js
Support compression and add the `compress` method which user can set the `compress` flag for a subsequent event emission.
> Support compression

- test/socket.io.js
this is a failing test for socket.io-client issue #1956 
the fix is located in pull request https://github.com/Automattic/socket.io-client/pull/808
> bugfix/1956 test for don't reuse same-namespace connections

- lib/client.js
- lib/socket.js
- package.json
- Change optional arguments to an option object.
- No use of `flags` on `Socket#packet` so that we don't need to clear `flags` within it.
-  Enable volatile and compress when broadcasting
Related: https://github.com/Automattic/socket.io-adapter/pull/26
> improve Socket#packet and Client#packet and enable volatile and compress when broadcast

- lib/index.js
- lib/namespace.js
- test/socket.io.js
Add `volatile` and `compress()` to namespace including aliases for `Server`.
Note: required to merge https://github.com/Automattic/socket.io/pull/2006 to pass all tests. 
Related: https://github.com/Automattic/socket.io/issues/1952, https://github.com/Automattic/socket.io/issues/1741, https://github.com/Automattic/socket.io-client/issues/742
> Supports flags on namespace

- lib/socket.js
When a socket connects, it joins its own room, resulting in a call to adapter.add.
The adapter in turn should be able to find the socket by id.
> Let adapter.add find connected socket

- Readme.md
Migrated legacy URLs containing 'Automattic' to the new org 'socketio'
> README: fixed up legacy repo links

- Readme.md
Remove broken build status caused by the name change of the github organization.
> Working travis build status

- .travis.yml
Hi!
As suggested [there](https://github.com/travis-ci/travis-ci/issues/2076), the npm version associated by default with node v0.8 does not support caret (^) operator, thus making the build fail.
Note: `sudo: false` allow the use of [container-based infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/)
> Upgrade npm version in order to fix node v0.8 build

- lib/socket.js
Socket#request is defined as getter, so we shouldn't try to set value.
Related: https://github.com/Automattic/socket.io/issues/2120
> Don't set request property

- package.json
[Package `ms` is vulnerable to DoS attacks](https://nodesecurity.io/advisories/46). The issue was fixed in `v0.7.1`.
Package `debug` was updated accordingly in `v2.2.0`.
This PR updates the required version of `debug` ([Node Security tools](https://www.npmjs.com/package/nsp) will complain and fail until this is fixed).
> Update “debug” to avoid vulnerability in “ms”

- lib/client.js
- lib/index.js
- lib/namespace.js
- lib/socket.js
- test/socket.io.js
> converted arrays to objects

- Readme.md
The documentation was a little confusing because it showed the socket.to() example under the socket.in() heading. I have made minor changes to be more clear.
> Clarified documentation of Socket.in

- lib/client.js
- lib/index.js
- lib/namespace.js
- lib/socket.js
- test/socket.io.js
Please excuse me for this poorly-written PR: https://github.com/socketio/socket.io/pull/2239
I added a test, but it will currently fail due to:
- https://github.com/socketio/engine.io/pull/367
- https://github.com/socketio/socket.io-client/pull/913
Please tell me if something is missing.
> Add hasOwnProperty checks

- lib/socket.js
- test/socket.io.js
Related:
* https://github.com/socketio/socket.io/pull/2312
* https://github.com/socketio/socket.io-redis/issues/53 (the second point should also be fixed as `this.rooms` is now an object)
> Trigger callback even when joining an already joined room

- History.md
- Readme.md
Related: https://github.com/socketio/socket.io/issues/2371
The website (http://socket.io/docs/server-api/) should be updated accordingly.
> Document type change of Socket#rooms

- .travis.yml
- Makefile
- gulpfile.js
- package.json
- Add `gulp` to repo
- Add `gulp` tasks to mirror `make` recipes
- Add `transpile` task for babel transformation
- Redirect all `make` recipes to `gulp`
- Remove node 0.8 from travis
Note: ESLint will be on the next PR as fixes for linting errors will make reviewing of PR difficult
> Add gulp and babel

- lib/socket.js
#2451 #2405 #2475 #2491 
This should fix break since b73d9be and #2239 
Since I'm not using namespaces, I need someone else help to check if this would break them.
> stop prepend /# before id when no namespace

- examples/chat/public/style.css
Not sure why `.username` was floated, but it causes the messages to steadily march to the right in Firefox, per screenshot:
Removing the float (or setting `.messages > * { clear: both; }`) results in identical, correct display in both Chrome and Firefox.
> Fix chat display in Firefox

- Readme.md
The documentation, inadvertently, causes confusion for newer programmers, hindering their learning curve and ability to learn `socket.io` faster.
This proposed change aims at preventing this confusion in order to allow new programmers easier access to resources, especially when searching the web for more information.
The name `socket` in the documentation refers to the API gateway, or the abstraction layer, related to the `client` and other properties. However, in the rest of the programming world, `sockets` usually refer to Berklee sockets or the lower-level communication channel that is used to implement Protocols such as the Websocket Protocol and HTTP.
New programmers often search for more informations using the `sockets` keyword when they are grappling with learning the `socket.io` …
> Documentation update to help new programmers

- Readme.md
- lib/socket.js
- test/socket.io.js
As suggested there https://github.com/socketio/socket.io/issues/1814 (all credits to @X-Coder)
```javascript
socket.on('disconnecting', function(){
var rooms = socket.rooms.slice();
// socket.rooms should not be empty here (on 'disconnect' it is, because `leaveAll()` has already been called)
});
```
> Add a 'disconnecting' event to access to socket.rooms upon disconnection

- Readme.md
Just a small change really. I noticed that clicking the badge unfortunately did not take me to the npm registry page. So here you go… Have a nice day.
> Link readme npm package badge to npm registry page

- lib/client.js
Currently these are caught by socket.io and treated as client errors. See https://github.com/socketio/socket.io/issues/2544#issuecomment-247599752
> Avoid swallowing exceptions thrown by user event handlers

- test/socket.io.js
I recreated the pull request.
cc: @darrachequesne
> Use client function to unify `client` in test script

- package.json
- test/socket.io.js
Tests seem to fail due to https://github.com/socketio/engine.io/pull/393.
> Bump engine.io to 1.7.1

- lib/index.js
- test/socket.io.js
The standard says that an ETag must be surrounded in double quotes:
https://tools.ietf.org/html/rfc7232#section-2.3
Although browsers tend to be lenient, omitting the quotes can confuse/break some kinds of proxies and other tools that demand compliant formatting. For example, Sandstorm.io enforces strict HTTP usage for security reasons and will block responses with invalid ETags.
> Make ETag header comply with standard.

- test/socket.io.js
Test 'should be able to close sio sending a port' defined a clientSocket
but didn't set 'reconnection: false'.
Now, the default behavior of a clientSocket is 'reconnection: true'.
As a result, the clientSocket was "leaked" from the test case
and seemed to intermittently connect to the servers in subsequent
test cases. This would cause other tests to timeout unexpectedly.
It's not clear to me why this would happen, since the test case
assigns a unique port number to the socket.
However, if you go into socket.io-client and assign and log
unique IDs to each socket, then you'll see that this clientSocket
shows up in other test cases if the reconnectionDelay strikes
unluckily.
A better fix might be to close the socket before exiting the test, but I'm not 100% sure how to do that since I don't …
> FIX Flaky test: Clean up a clientSocket

- lib/index.js
Previously, only `on` and `emit` methods were supported by Socket.IO server. This PR iterates over all EventEmitter methods and proxies them over to the main namespace.
> Server supports all event emitter methods

- Readme.md
- lib/index.js
Previously unable to pass a `done` callback to the `Server#close()` method.
Now able to pass a `done` callback to the `Server#close()` method.
candidate for #2739
> Feature - added support for Server#close(callback)

- lib/socket.js
- package.json
Right now parameters passed during handshake, such as tokens, are being dropped.
Parameters are preserved as intended
Fixes #2712
> Don't drop query variables on handshake

- examples/chat/README.md
- examples/chat/index.js
- examples/chat/package.json
- examples/chat/public/main.js
- make the example autonomous (`npm install && npm start`)
- add disconnect/reconnect logs (and send username on reconnection)
> Update the chat example

- lib/index.js
This fix allows server to serve the sourcemap of socket.io-client generated by webpack builder using `gulp build` task.
The corresponding PR for `socket.io-client` is https://github.com/socketio/socket.io-client/pull/953
Tested in Chrome and Firefox using a custom package of `socket.io-client` with sourcemap file. It also catches the error when there is not sourcemap available in `socket.io-client`.
Screenshots of how the generated source map looks in browsers:
> serve sourcemap for socket.io-client

- lib/index.js
Null can be passed as "srv" argument and will fail on "srv.listen" check.
> Prevent null from being accepted as argument

- docs/API.md
> fix a typo on `clients` method in the API documentation

- docs/API.md
> add an example for socket.join() method

- docs/API.md
> Add pingInterval/pingTimeout/transports options in the API documentation

- lib/namespace.js
- lib/socket.js
Deleting properties is a v8 'optimization killer'
> Reset properties instead of deleting them

- lib/client.js
Encoder per connection
Single encoder
> Share encoder

- lib/client.js
- test/socket.io.js
Currently the server treats the connection as closed but never actually closes it. See #2544
> Properly close the connection on error

- examples/cluster-nginx/README.md
- examples/cluster-nginx/docker-compose.yml
- examples/cluster-nginx/nginx/Dockerfile
- examples/cluster-nginx/nginx/nginx.conf
- examples/cluster-nginx/server/Dockerfile
- examples/cluster-nginx/server/index.js
- examples/cluster-nginx/server/package.json
- examples/cluster-nginx/server/public/index.html
- examples/cluster-nginx/server/public/main.js
- examples/cluster-nginx/server/public/style.css
> Add nginx cluster example

- examples/cluster-httpd/README.md
- examples/cluster-httpd/docker-compose.yml
- examples/cluster-httpd/httpd/Dockerfile
- examples/cluster-httpd/httpd/httpd.conf
- examples/cluster-httpd/server/Dockerfile
- examples/cluster-httpd/server/index.js
- examples/cluster-httpd/server/package.json
- examples/cluster-httpd/server/public/index.html
- examples/cluster-httpd/server/public/main.js
- examples/cluster-httpd/server/public/style.css
> Add httpd cluster example

- Readme.md
Related: https://github.com/socketio/socket.io/issues/2823
> Add 'Features' section in the README

- lib/index.js
Browserify doesn't supports require.resolve, and as a consequence, makes nexe fails the compilation : 
This PR attempts to read the content of the socket.io-client file via fs.readFileSync and falls back to the original require.resolve if this file cannot be found. 
https://github.com/nexe/nexe/issues/289
> Use fs.readFileSync instead of require.resolve

- docs/API.md
- lib/client.js
- lib/index.js
* a new feature
This would enable the use of some custom parsers, like the following based on msgpack:
```js
const msgpack = require('notepack.io');
const Emitter = require('component-emitter');
class Encoder {
encode(obj, callback){
var encoded = msgpack.encode(obj);
callback([encoded]);
}
}
class Decoder extends Emitter {
add(obj){
var decoded = msgpack.decode(obj);
this.emit('decoded', decoded);
}
destroy(){}
}
exports.Encoder = Encoder;
exports.Decoder = Decoder;
```
And then:
```js
const server = require('http').createServer();
const myCustomParser = require('./my-custom-parser');
const io = require('socket.io')(server, {
parser: myCustomParser
});
```
That would also provide a workaround for https://github.com/socketio/socket.io-parser/issues/61.
Related: …
> Allow the use of a custom parser

- Readme.md
I used the express setup with my latest project and stumbled into an error, that was hard to fix, because it was so small and crucial.  
I accidently called `app.listen(PORT)` instead of `server.listen(PORT)`  
This basically leads to working Express functionality and routes, but the `/socket.io` route will not be present and thus the GET request for any client willing to connect gets a 404.  
I hope this small comment may save another one the four hours I spent on tracing my mistake.
> Small addition to the Express Readme Part

- lib/index.js
- lib/socket.js
- test/socket.io.js
* a new feature
Related:
- https://github.com/socketio/engine.io/pull/471
- https://github.com/socketio/socket.io/issues/1954
> Merge Engine.IO and Socket.IO handshake packets

- package.json
Includes the following (from engine.io changelog):
* [fix] Initialize the WebSocket server in the Server constructor ([#476](https://github.com/socketio/engine.io/issues/476))
* [chore] Bump ws to version 1.1.2 (vulnerability fix) ([#480](https://github.com/socketio/engine.io/issues/480))
Socket.io installs version 2.0.0 of the engine.io dependency.
Socket.io installs version 2.0.2 of the engine.io dependency.
IMHO it's worth considering changing this dependency to `'engine-io': '~2.0.0'` to avoid having to make new releases of `socket.io` every time `engine.io` is patched, since both modules are maintained by the same group.  But I can appreciate the desire to lock things down hard.
> Bump engine.io to version 2.0.2

- examples/webpack-build-server/README.md
- examples/webpack-build-server/lib/index.js
- examples/webpack-build-server/package.json
- examples/webpack-build-server/support/webpack.config.js
- examples/webpack-build/README.md
- examples/webpack-build/index.html
- examples/webpack-build/lib/index.js
- examples/webpack-build/package.json
- examples/webpack-build/support/noop.js
- examples/webpack-build/support/webpack.config.js
- examples/webpack-build/support/webpack.config.slim.js
Related: https://github.com/socketio/socket.io/issues/2109 https://github.com/socketio/socket.io/issues/2823
> Add WebPack build example

- docs/API.md
- lib/socket.js
- package.json
- test/socket.io.js
* a new feature
Enable the following: 
`socket.join(['room1', 'room2']);`
Closes https://github.com/socketio/socket.io/issues/2466, closes https://github.com/socketio/socket.io/issues/2877
> Allow to join several rooms at once

- docs/emit.md
- The information currently present in the cheat sheet does not show users how they can emit to a room that is within a namespace.
- Adds an example of how someone would emit to a room within a namespace.
> [docs] Update emit cheatsheet

- docs/API.md
- docs/README.md
It had showed four pound signs, now it is bold. I fixed it by deleting and re-adding the space in between the pounds and the text. Not sure why that was the issue, but I fixed it nonetheless.
Showed four pound signs
It's bold now
None
> Fixed "Getting Started" not being bold

- lib/namespace.js
- lib/socket.js
- package.json
- test/socket.io.js
Following https://github.com/socketio/socket.io-parser/pull/66 and https://github.com/socketio/socket.io-client/pull/1103.
Because the `hasBinary` check may be useless for some parser (like [socket.io-msgpack-parser](https://github.com/darrachequesne/socket.io-msgpack-parser)).
Also closes https://github.com/socketio/socket.io/issues/2871
> Move binary detection to the parser

- examples/custom-parsers/README.md
- examples/custom-parsers/package.json
- examples/custom-parsers/public/index.html
- examples/custom-parsers/src/client1.js
- examples/custom-parsers/src/client2.js
- examples/custom-parsers/src/client3.js
- examples/custom-parsers/src/client4.js
- examples/custom-parsers/src/custom-parser.js
- examples/custom-parsers/src/server.js
- examples/custom-parsers/support/webpack.config.js
> Add an example of custom parser

- lib/namespace.js
- lib/socket.js
- test/socket.io.js
Using a middleware could previously lead to a connecting client
receiving a connect event from the server before the server triggers
its own connect event.
Fixes https://github.com/socketio/socket.io/issues/2935.
> fix timing issues with middleware

- Readme.md
1. Update URL of badge to [https://slackin-socketio.now.sh/badge.svg](https://slackin-socketio.now.sh/badge.svg)
1. Update URL To slack channel [https://slackin-socketio.now.sh](https://slackin-socketio.now.sh)
> Update slack badge as it's broken.

- lib/index.js
- lib/namespace.js
- test/socket.io.js
Fix `TypeError: Cannot convert undefined or null to object` when a middleware is added before the engine is properly attached.
Closes https://github.com/socketio/socket.io/issues/2963.
> fix middleware initialization

- lib/socket.js
It seems packets could be delivered to wrong room in some case, if the `_rooms` array was not reset before the next emit.
Closes https://github.com/socketio/socket.io/issues/2962.
> reset rooms object before broadcasting

- docs/API.md
> [docs] Fix misnamed 'Object.keys' in API docs

- lib/socket.js
- test/socket.io.js
Closes https://github.com/socketio/socket.io/issues/3036
> do not throw when receiving an unhandled error packet

- docs/API.md
- docs/emit.md
- lib/index.js
- lib/namespace.js
- lib/socket.js
- package.json
So that the call to the `has-binary` method can be skipped. Usage:
```
// with binary data
socket.binary(true).emit("binary", obj);
// without binary data
socket.binary(false).emit("string", obj);
// call to hasBin
socket.emit("guess", obj);
```
From https://github.com/socketio/socket.io/pull/2838.
> [feat] Add a 'binary' flag

- docs/API.md
- lib/client.js
- lib/index.js
- test/socket.io.js
Rebased from https://github.com/socketio/socket.io/pull/1921.
> [feat] Add support for dynamic namespaces

- Readme.md
> add a Dart client implementation.

- lib/namespace.js
- package.json
- test/socket.io.js
When using a custom namespace with a middleware, the client did not receive the 'connect' event.
> [fix] Properly emit 'connect' when using a custom namespace

- docs/API.md
- lib/index.js
- test/socket.io.js
Previously, the protocol was not taken in account, which caused the following behaviour:
```js
io.origins('https://foo.example.com:443'); // ok as a string
io.origins(['https://foo.example.com:443'); // not ok as an array
```
Fixes #3190
> [fix] Include the protocol in the origins check

- docs/API.md
The docs for `origins(fn)` currently don't mention that `error` has to be supplied as a string.  This really tripped me up as I was supplying an Error instance as I usually do for callbacks, which crashes w/ certain versions of Node.
Added line to documentation indicating that `error` should be a string.
An alternative to this would be to patch `engine.io` to allow an Error instance in its [abortConnection method](https://github.com/socketio/engine.io/blob/bd1e81ec3d11f18c5fc09c55745d5ff66d037cc1/lib/server.js#L497), using its `message` property as the error message.
> Add note in docs for `origins(fn)` about `error` needing to be a string.

- docs/emit.md
The previous version was confusing, as `socket.to(socket.id).emit()` does nothing.
Fixes #3220
> clarify private messaging in the emit cheatsheet

- examples/chat/index.js
- examples/chat/public/main.js
Not ES6 formatted
Is now ES6 formatted
ES6 ftw
> Updated to ES6

- lib/socket.js
Currently, the only way to set the local flag when in socket context is as follow
```js
socket.flags['local'] = true;
```
Now we can add the local flag the same way we do it on the Namespace object
```js
socket.local...
```
https://github.com/socketio/socket.io/issues/3217
> add local flag to the socket object

- lib/namespace.js
Accessing the clients of a dynamic namespace throws because doing io.of(/your-regex/g) returns a namespace with no adapter and the clients methods tries to access namespace.adapter.clients
Clearer error
> Throws an error when trying to access the clients of a dynamic namespace

- lib/index.js
No cache-control header is sent when requesting clien script
Server will send cache-control header with value "public, max-age=0"
> add cache-control header to client source

- docs/API.md
I was struggling with CORS issues using explicitly the default origins value `*` on development, a value that is retrieved from a `.env` file, but turns out that the default is actually `*:*`.
origins (String): the allowed origins (`*`)
origins (String): the allowed origins (`*:*`)
> Fix documentation about default origins value. Update API.md

- docs/API.md
- examples/custom-parsers/README.md
- examples/custom-parsers/src/server.js
- test/socket.io.js
Buffer() is deprecated warning message in test
No warning message in test
> Buffer is deprecated fix

- Readme.md
I just found out that there is no reference on the Readme about how to integrate Socket.io on [Fastify](https://www.fastify.io/).
Here is the plugin [link](https://github.com/alemagio/fastify-socket.io).
> docs: added to readme reference to fastify integration

- lib/index.ts
Needed interfaces/types are not exposed. `@types/socket.io` used to export these.
Exported needed types.
Noticed while upgrading. Will create a similar PR to `socket.io-client`.
May want to consider adding the type modifier to the export, so that the actual abstractions won't be exposed. Downside: it will make the `.d.ts` only compatible with ts@2.8+.
You using TypeScript and publishing built-in `.d.ts` is awesome.
> fix(typings): expose additional needed types

- package-lock.json
- package.json
* **a bug fix**
* ~a new feature~
* ~an update to the documentation~
* ~a code change that improves performance~
* ~other~
Tests fail on Windows because of the use of single quotes in NPM scripts where Windows only accepts double quotes and because of a bug in NYC that was fixed in 15.0.0.
Tests run and succeed as expected.
Full logs of fix + new results:
```sh
C:\ws\socketio>npm outdated
Package           Current    Wanted    Latest  Location
@types/mocha        8.0.3     8.0.4     8.0.4  socket.io
@types/node       14.14.7  14.14.10  14.14.10  socket.io
debug               4.1.1     4.1.1     4.3.1  socket.io
engine.io           4.0.1     4.0.4     4.0.4  socket.io
eslint             7.12.1    7.14.0    7.14.0  socket.io
mocha               3.5.3     3.5.3     8.2.1  socket.io
nyc …
```
> Make tests work on Windows

- lib/client.ts
- lib/index.ts
- lib/namespace.ts
- lib/parent-namespace.ts
- lib/socket.ts
- package-lock.json
- package.json
- test/socket.io.ts
- test/support/util.ts
- tsconfig.json
- upgrade prettier to 2.2.0 to gain support for TypeScript's
new type-only-imports feature.
tests are passing on my local machine (I was a bit confused by the two expected errors at first). You may want to regenerate package-lock.json yourself if you have (what I think is) a healthy level of distrust. I didn't add a malicious package to it, but there's nothing to immediately stop me from doing so.
> add more typing info and upgrade prettier

- wrapper.mjs
Exports the Namespace and Socket type from MJS wrapper
MJS wrapper only exports Server
MJS wrapper exports Server, Namaspace and Socket types 
I would say is a continuation of PR https://github.com/socketio/socket.io/pull/3684 and my comment there
https://github.com/socketio/socket.io/pull/3684#issuecomment-729396811
> Exports the Namespace and Socket type v3

- .replit
- Readme.md
This pull request adds a `Run on Repl.it` badge to the `README`. This will allow users to easily run this repository in their browser, without having to set up an environment. You can learn more about Repl.it [here](https://repl.it).
> Add run on repl.it badge to README

- examples/chat/public/main.js
- Add default initializers
- Use let and const instead var
The chat example can be updated with ES6 features like default params, constants (avoiding the use of `var`), and template literals.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
The chat example with these three features.
> Improve the chat example with more ES6 features

- Readme.md
```markdown
- [Java](https://github.com/socketio/socket.io-client-java)
- [C++](https://github.com/socketio/socket.io-client-cpp)
- [Swift](https://github.com/socketio/socket.io-client-swift)
- [Dart](https://github.com/rikulo/socket.io-client-dart)
```
```markdown
- [Java](https://github.com/socketio/socket.io-client-java)
- [C++](https://github.com/socketio/socket.io-client-cpp)
- [Swift](https://github.com/socketio/socket.io-client-swift)
- [Dart](https://github.com/rikulo/socket.io-client-dart)
- [Python](https://github.com/miguelgrinberg/python-socketio)
- [.Net](https://github.com/Quobject/SocketIoClientDotNet)
```
<https://socket.io/docs/#Other-client-implementations>
> Add implementations to Readme.md according to the documentation

- examples/chat/public/main.js
Clients do not render participants messages due addChatMessage is trying to access to un initiated options to set fade to false
Now renders
> fix: init options at addChatMessage

- examples/angular-todomvc/server.ts
- examples/typescript/server.ts
`socket` is inferred as type `Socket` as of 4.0.0; it was previously inferred as `any`. The type annotation is no longer needed to cast the `any` to `Socket`.
The `Socket` type annotation can be safely removed. The behavior is unchanged, but it's less code.
Typed events in socket.io 4.0 remove the need for writing type annotations in callbacks of reserved events.
> Remove unnecessary type annotations in examples

- lib/typed-events.ts
- test/socket.io.test-d.ts
Due to a compiler bug, we had the following issue (see #3833):
```ts
import { Server } from "socket.io";
const io = new Server(3000, {});
// this works fine
io.on("connection", (socket) => {});
enum Event {
CONNECTION = "connection",
}
// Fails to compile!
// Argument of type '(socket:Socket) => void' is not assignable to parameter of type 'never'.
// ts(2345)
io.on(Event.CONNECTION, (socket) => {});
```
The above code now compiles. However, in the line `io.on(Event.CONNECTION, (socket) => {});`, the lambda parameter `socket` is inferred to be of type `any` instead of `Socket` if an enum member is used. 
Note that this only affects the situation where an enum member is used: If a string literal is used, the correct type (`Socket`) is still inferred.
Also note that inferring `any` in this …
> Fix #3833: Add fallback to untyped event listener

- examples/basic-crud-application/server/package.json
test/todo-management/todo.tests.ts:275:3 - error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
> add missing module

- lib/index.ts
- test/socket.io.ts
Client JavaScript will not be served if the request URL contains a query string.
Client JavaScript will be served, even if the request URL contains a query string.
Resolves socketio/socket.io#4023
> feat: ignore the query string when serving client JavaScript

- lib/client.ts
- lib/index.ts
- lib/namespace.ts
- lib/parent-namespace.ts
- lib/socket.ts
`Socket.data` is `any`
`Socket.data` is `any` by default but `Partial<ProvidedType>` if a type is provided in the `Server` and/or `Socket` constructors
I had to wrap the provided type in `Partial` because we are initializing the `Socket.data` with `{}`. I did not want to alter this behavior but instead I just wanted to provide a simple way to type the `Socket.data` field. This fixes #4155.
> Add type information to `Socket.data`

- examples/chat/README.md
- examples/chat/public/main.js
The source code of the example app `examples/chat`  implies that reconnetion status (failure or success) is shown to the user.
In fact, it's not, because the reconnection events are listened to incorrectly: you're supposed to listen to the Manager's events like `socket.io.on(...)`, not just `socket.on(...)`.
I only wanted to take a look at how to handle disconnections and do reconnections, but here is what it came down to :)
The example works as it's supposed to, you can now see messages like "attempt to reconnect has failed" in the UI.
Also updated README in the example: it says you need to run `npm ci` to install packages, but since lockfiles are gitignored in the `example` folder, you actually need to run `npm i`
> Fix reconnection handling in the chat demo app

- package.json
Using `typescript@4.6.0-dev.20211225` and `"moduleResolution": "nodenext"` we are unable to resolve types of `socket.io`
Make TypeScript successfully resolve types
See https://github.com/microsoft/TypeScript/issues/46770#issuecomment-966612103 for detail, in `nodenext` module resolution it requires a `types` field in `exports` with full filename including extension
> fix: add types to exports field to be compatible with nodenext module resolution

- lib/index.ts
Fixes #4229
https://github.com/socketio/socket.io/issues/4229#issuecomment-1003607352 will be done in another PR
> chrore(types): fix `SocketData` is not passed down to `Namespace`

- lib/broadcast-operator.ts
- lib/index.ts
- lib/namespace.ts
- lib/parent-namespace.ts
- lib/socket.ts
Adds https://github.com/socketio/socket.io/issues/4229#issuecomment-1003607352
> chore(types): make `RemoteSocket.data` type safe

- lib/socket.ts
#4138 added an `Event` type using Typescript’s labelled tuple syntax:
```ts
type Event = [eventName: string, ...args: any[]];
```
This fails to compile if a consumer is using a TypeScript version less than 4.x
Reference: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#labeled-tuple-elements
This PR removes the labelling in the `Event` type to continue to support TypeScript 3.x as did 0cb6ac9.
> fix(typings): ensure compatibility with TypeScript 3.x

- package-lock.json
- package.json
Runned npm audit fix in order to update the engine.io dependency version. The new version fixes the vulnerability [CVE-2022-21676](https://github.com/socketio/engine.io/security/advisories/GHSA-273r-mgr4-v34f)
> Npm audit changes to fix engine.io vulnerability CVE-2022-21676

- examples/create-react-app-example/src/App.js
Previous create-react-app example can work normally. However, the `useEffect` hook will work multiple times when a new message arrives.
I add two console log to show the problem (line 14 and 26 in [Gist](https://gist.github.com/wdwang09/931347966471780437a5d0288269a1d7)).
Socket.IO callback will change the states, so the React component updates and call `useEffect` again.
I fix this problem by passing a second argument to `useEffect` ([doc](https://reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects)). When states change, don't run `useEffect` again.
Other change: I add the logo and other elements generated by create-react-app.
> docs(examples): update create-react-app example

- lib/namespace.ts
Hi there! 👋
TypeScript recently added some stricter checking around unconstrained generics being incompatible with emptyish object types. The changes are only in nightly versions of TypeScript right now, but we've been exploring how open-source projects have been impacted. These are the changes necessary for socket.io to build cleanly in TypeScript 4.8.
> Propagate constraints from `NamespaceReservedEventsMap` to `ServerReservedEventsMap`

- lib/index.ts
This adds typings for the socket.io `engine` field, which offers better IntelliSense when retrieving the server, as well as more confidence on the developer-side of what types of fields are entering the server.
This fixes #4590.
> fix(types): add typings for io.engine

- Readme.md
This adds the [rust-socketio](https://github.com/1c3t3a/rust-socketio) implementation to the list of socket.io implementations.
> docs: add rust-socketio implementation

- lib/socket.ts
- package-lock.json
- test/namespaces.ts
Change is fixing bug described here: https://github.com/socketio/socket.io/issues/4772
> Clean up namespaces after client is rejected in middleware

- .vscode/settings.json
- lib/broadcast-operator.ts
- lib/index.ts
- lib/namespace.ts
- lib/parent-namespace.ts
- lib/socket.ts
- lib/typed-events.ts
- package-lock.json
- package.json
- test/socket.io.test-d.ts
- test/socket.ts
- test/support/util.ts
The types of the `emit`, `emitWithAck`, `serverSideEmit`, and `serverSideEmitWithAck` have issues with their types.
They revert to `any` very often or aren't arrays when they should be (server/namespace emit and server/namespace => broadcastOperator emit).
This fixes most of this behavior and adds tests for them.
Fixes #4813
> improve emit types

- lib/index.ts
http server should accept non-secure http2server instance
> fix(typings): accept an Http2Server non-secure as http-server instance

- lib/typed-events.ts
- test/connection-state-recovery.ts
- test/messaging-many.ts
- test/namespaces.ts
- test/socket-timeout.ts
- test/socket.io.test-d.ts
- test/support/expectjs.d.ts
- test/support/util.ts
- test/uws.ts
Typescript type fixe relating to #4817, also type failures in the tests due to the client#id type becoming `string|undefined` ([f9c16f2](https://github.com/socketio/socket.io-client/commit/f9c16f226512fc8a8df461e3a07e392720462165))
```ts
import { Server } from "socket.io";
interface ServerToClientEvents {
noArg: () => void;
}
const io = new Server<{}, ServerToClientEvents>();
io.emit("noArg"); // <- Error
```
```ts
import { Server } from "socket.io";
interface ServerToClientEvents {
noArg: () => void;
}
const io = new Server<{}, ServerToClientEvents>();
io.emit("noArg"); // ✔️ - no error!
```
#4914
> Fix: Calling io.emit("event") with events that have no arguments results in TypeScript errors

- lib/parent-namespace.ts
`parentNamespace.adapter` be a dummy adapter-like object, and only supports `broadcast` operation.
The same behavior, but with a class that will pass type check.
When reading the code I saw the FIXME, so I thought the type check can be satisfied this way.
IMO except the type check the inline `{broadcast}` adapter was not bad. It is arguably better in that unsupported operations will fail loudly instead of silently. So I'm not very confident of this PR. Opinions welcome 🙏🏽 .
To pass type check while preserving the old fail-fast behavior, one could also `this.adapter = {broadcast} as Adapter;`
> parent-namespace: change inline Adapter-like to file-private class

- lib/parent-namespace.ts
- test/namespaces.ts
When a dynamic namespace emits to an individual socket, it will be met with an error:
```
node_modules/socket.io/dist/parent-namespace.js:88
this.children.forEach((nsp) => {
^
TypeError: Cannot read properties of undefined (reading 'forEach')
at ParentBroadcastAdapter.broadcast (node_modules/socket.io/dist/parent-namespace.js:88:23)
at BroadcastOperator.emit (node_modules/socket.io/dist/broadcast-operator.js:169:26)
at Socket.<anonymous> (server.js:60:33)
at Socket.emit (node:events:520:28)
at Socket.emitReserved (node_modules/socket.io/dist/typed-events.js:56:22)
at Socket._onclose (node_modules/socket.io/dist/socket.js:547:14)
at Client.onclose (node_modules/socket.io/dist/client.js:247:20)
at Socket.emit (node:events:532:35)
at Socket.onClose …
```
> fix: ParentNamespace adapter broadcast bug

- lib/index.ts
- test/support/util.ts
```ts
import { Server } from "socket.io";
const io = new Server(3000, { /* options */ });
io.httpServer // Property 'httpServer' is private and only accessible within class 'Server<ListenEvents, EmitEvents, ServerSideEvents, SocketData>'.ts(2341)
```
```ts
import { Server } from "socket.io";
const io = new Server(3000, { /* options */ });
io.httpServer // now is accessible as the documentations says (https://socket.io/docs/v4/server-initialization/#standalone)
```
https://github.com/socketio/socket.io/issues/5034
> Fixes #5034 - change private property io.httpServer to a public property

- package-lock.json
refs:
- https://www.tenable.com/cve/CVE-2024-37890
- https://github.com/websockets/ws/releases/tag/8.17.1
Open CVE blocks auditing: https://github.com/socketio/socket.io/issues/5051
Bumps the websockt package to remove security issues
> fix: bumps ws to version 8.17.1 to fix CVE-2024-37890

- packages/engine.io-client/lib/socket.ts
ah! I tried to specify transports, but it doesn't autocomplete.
Because current type of transport is string[].
I have to check JSDOC to see  ['polling','websocket', 'webtransport'].
Be comfortable with auto-completion without typos.
#5187
> refactor: default transport in type

- package-lock.json
- packages/engine.io/package.json
An existing dependency "[cookie](https://www.npmjs.com/package/cookie)" has a vulnerability.
- "cookie" has been updated to a version that fixes the vulnerability.
- The contents of the `package-lock.json` seem to have been inconsistent (see diff). I ran `npm i` to correct it.
close #5206
https://github.com/advisories/GHSA-pxg6-pf52-xh8x
https://avd.aquasec.com/nvd/2024/cve-2024-47764/
https://security.snyk.io/vuln/SNYK-JS-COOKIE-8163060
> chore(deps): update cookie to 0.7.2

- packages/socket.io/lib/namespace.ts
- packages/socket.io/lib/parent-namespace.ts
Issue: #5179
**This is a variant for PR #5195, please only merge one of these!** I created two PRs for the related issue, providing both suggested solutions. This one uses the index signature trick as suggested in the issue.
I tried adding a test to prevent regression, but didn't manage to reproduce the error that caused all this inside the socket.io test suite. I assume this is because we use a stricter TypeScript configuration in our own codebase, but didn't bother verifying it.
> fix: make Namespace._fns private

- packages/engine.io-client/lib/transports/websocket.node.ts
```
SyntaxError: Named export 'WebSocket' not found. The requested module 'ws' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from 'ws';
const { WebSocket } = pkg;
```
Works
Hitting this in https://github.com/immich-app/immich
I also saw a couple projects hitting this error when searching online, but didn't look closely at them to see if they're using `socket.io`/`engine.io`:
- https://web3auth.io/community/t/web3auth-version-7-0-4-build-issues-resolved/5789
- https://github.com/wevm/viem/issues/1202
> fix: correctly consume `ws` package
